spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "health, info"
  endpoint:
    health:
      show-details: always
      access: read_only
    info:
      access: read_only