spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: testpassword
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

# actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      access: read_only
